### ISSUE TITLE
Doesn't work on Python3.

### ISSUE THREAD

**Issue by Natfan** [ryankrage77/RandomWordGenerator#1]
Please add forward compatibility?

**Comment by ryankrage77** [comment]
Mentioned in latest README update.

May be fixed thanks to added shebang line, not tested.

Will be fixed in next version, current workaround is to run using 2.7, i.e;

`python2 RandomWordGenerator.py`

**Comment by ryankrage77** [comment]
Added python 3 support, dropped python2 support.

tested and working in 3.6.4
